Substra/orchestrator

.github/workflows/docker.yml

This will publish images on public github registry.
Untested, let's run the workflow.

ci(docker): publish images on github registry

---

.github/workflows/docker.yml

Publish images under substra organization.

ci(docker): publish image under substra organization

---

charts/orchestrator/README.md

docs(chart): fix organization link in readme

---

.github/workflows/doc.yml
.github/workflows/end2end.yml

Update golang-migrate to its latest release.
- counting on CI

ci: update migrate

---

charts/README.md
charts/orchestrator/README.md

Fixes a broken link on this page https://artifacthub.io/packages/helm/substra/orchestrator
Fixes the documentation in the repo.
It's ok if the CI does not pass these changes will be released with the next chart version.

docs: update changelog link in chart readme

---

CHANGELOG.md

Minor PR to harmonize the changelog

style(changelog): add linebreaks

---

.github/workflows/doc.yml

Make doc auto commits compliant with DCO.

ci(doc): signoff DB schema commits

---

e2e/computetask_test.go

Since parent tasks are determined from inputs, their order doesn't impact the computation. There is no guarantee on parent task order.

test: remove parent task key order check

---

docker/orchestrator-chaincode-init/dependencies.json

Fixes image build error for init image
- local docker build

fix(docker): update curl version

---

docker/orchestrator-chaincode-init/dependencies.json

chore(deps): update apt/apk dependencies in Dockerfile orchestrator-chaincode-init

---

.github/workflows/dependencies.yml

This should make docker dependencies update PRs compliant with DCO.
Example of such PR: #72
Untested

ci: signoff docker dependencies updates

---

docker/orchestrator-chaincode/dependencies.json
docker/orchestrator-server/dependencies.json

chore(deps): update apt/apk dependencies in Dockerfile orchestrator-chaincode-and-server

---

charts/orchestrator/Chart.yaml

Signed-off-by: ThibaultFy <50656860+ThibaultFy@users.noreply.github.com>

chore: update chart mainteners

---

docker/orchestrator-chaincode-init/dependencies.json
docker/orchestrator-chaincode/dependencies.json
docker/orchestrator-server/dependencies.json

chore(deps): update apt/apk dependencies in Dockerfile orchestrator-chaincode

---

docker/orchestrator-chaincode/dependencies.json
docker/orchestrator-server/dependencies.json

concate https://github.com/Substra/orchestrator/pull/200 and https://github.com/Substra/orchestrator/pull/199

fix: update apt/apk dependencies in Dockerfile server and chaincode

---

CHANGELOG.md

chore: correct changelog

---

examples/k8s/cm-tls-org-1-cacert.yaml
examples/k8s/cm-tls-org-2-cacert.yaml
examples/k8s/cm-tls-org-3-cacert.yaml
skaffold.yaml

fix(skaffold): skaffold config requires

---

CHANGELOG.md
charts/orchestrator/CHANGELOG.md
charts/orchestrator/Chart.yaml

chore: release 0.36.1

---

charts/orchestrator/CHANGELOG.md
charts/orchestrator/Chart.yaml
charts/orchestrator/templates/_helpers.tpl
charts/orchestrator/templates/deployment.yaml
charts/orchestrator/templates/job-migrations.yaml

The container details for `wait-postgresql` are moved to the Helm Helper templates

refactor(helm): refactor wait-postgresql

---

charts/orchestrator/Chart.lock

fix(charts/orchestrator): postgresql 13.0.0 -> 13.1.2

---

.github/workflows/end2end.yml
.github/workflows/go.yml
docker/orchestrator-chaincode-init/Dockerfile
docker/orchestrator-chaincode-init/dependencies.json
docker/orchestrator-chaincode/Dockerfile
docker/orchestrator-chaincode/dependencies.json
docker/orchestrator-server/Dockerfile
docker/orchestrator-server/dependencies.json
go.mod
go.sum

chore: bump go version to 1.21

---

.github/workflows/go.yml
Makefile
chaincode/failurereport/contract_test.go
chaincode/ledger/event.go
lib/persistence/computeplan_dbal.go
lib/service/failure_report_test.go
server/distributed/adapters/event.go

Closes [FL-1244](https://linear.app/owkin/issue/FL-1244/add-code-formatting-for-orchestrator)
- `go` GitHub Action workflow updated checking code format added
- `Makefile` updated `format` target added and `lint` target updated to check the formatting  
- Source code formatted with `make format` target

chore: Add source code formatting

---

README.md

Update `README` with Go 1.21+ and add `goimports` in tools

docs(readme): bump go version and add goimports

---

CHANGELOG.md
docs/api.md

fix: incorrect "lib/assets" link in doc

---

CHANGELOG.md
docs/assets/computetask.md
e2e/client/client.go
lib/service/computetask.go
lib/service/computetaskstate.go
lib/service/computetaskstate_test.go

fix: function action propagation

---

.github/workflows/helm.yml

Closes FL-1240
- Checking if `Chart.lock` file is also updated
- Existing helm GitHub Action workflow refactored to use `substra/substra-gha-workflows/.github/workflows/helm.yml`.

refactor(ci): refactor existing helm gha workflow

---

.github/workflows/conventional-pr.yml

Refactors `conventional_title` GHA workflow from generic workflow from `substra-gha-workflows`

refactor(ci): use conventional-pr workflow from substra-gha-workflows

---

CHANGELOG.md
charts/orchestrator/CHANGELOG.md
charts/orchestrator/Chart.yaml

chore: release 0.38.0

---

.github/workflows/helm.yml

chore: add workflow_dispatch on helm publish

---

.github/workflows/end2end.yml

Fixes FL-1464
With a dummy tag `0.0.0` : https://github.com/Substra/orchestrator/actions/runs/8067779167/job/22039023280

fix: setup postgresl with right version

---

changes/394.changed
changes/395.changed
charts/orchestrator/CHANGELOG.md
charts/towncrier.toml

chore: add towncrier for charts changelog

---

charts/orchestrator/CHANGELOG.md
charts/orchestrator/Chart.yaml
charts/orchestrator/README.md
charts/orchestrator/values.yaml

chore: add resources requests and limits to containers

---

charts/orchestrator/CHANGELOG.md
charts/orchestrator/Chart.yaml
charts/orchestrator/templates/deployment.yaml
examples/k8s/cm-tls-org-1-cacert.yaml
examples/k8s/cm-tls-org-2-cacert.yaml
examples/k8s/cm-tls-org-3-cacert.yaml

Move some secret values from configmaps to secrets
Fixes FL-1521
- https://github.com/Substra/substra-backend/pull/889
[CI](https://github.com/Substra/substra-backend/pull/889#issuecomment-2058149926)

chore: move more configs to secrets

---

docker/orchestrator-server/dependencies.json

chore(deps): update apt/apk dependencies in Dockerfile orchestrator-server

---

charts/orchestrator/CHANGELOG.md
charts/orchestrator/Chart.yaml
charts/orchestrator/templates/job-migrations.yaml
charts/orchestrator/templates/networkpolicy-database.yaml
charts/orchestrator/templates/networkpolicy-deny-all.yaml
charts/orchestrator/templates/networkpolicy-orchestrator-client.yaml
charts/orchestrator/templates/networkpolicy-orchestrator-common.yaml
charts/orchestrator/templates/networkpolicy-orchestrator-server.yaml

Fixes FL-1457
- https://github.com/Substra/substra-backend/pull/875
[CI there](https://github.com/Substra/substra-backend/pull/875)

chore: network policy

---

charts/orchestrator/CHANGELOG.md
charts/orchestrator/Chart.lock
charts/orchestrator/Chart.yaml

chore: upgrade chart dependencies

---

changes/427.fixed
e2e/computeplan_test.go
lib/service/computetaskstate.go
server/standalone/dbal/computeplan.go
server/standalone/dbal/computeplan_test.go

closes FL-1577
closes FL-1130
New test has been added. Fail without the new implementation

fix: IsPlanRunning now check failed and canceled CP

---

charts/orchestrator/CHANGELOG.md
charts/orchestrator/Chart.yaml
charts/orchestrator/values.yaml

fix: remove postgresql user default

---

CHANGELOG.md
changes/427.fixed
changes/432.changed
changes/432.fixed
charts/orchestrator/CHANGELOG.md
charts/orchestrator/Chart.yaml

chore: release 0.42.0

---

changes/1666.fixed

fix: missing changelog content 1666
