.github/workflows/end2end.yml

On tag publication we upload a golden snapshot of the DB, but it currently fails because gcloud CLI is not setup on tags:
https://github.com/Substra/orchestrator/runs/8225048401?check_suite_focus=true
This attempts to fix the issue by enabling the setup steps on tag events.
- with a [test tag to trigger the workflow](https://github.com/Substra/orchestrator/runs/8225476435?check_suite_focus=true)

ci: setup google cloud on tags

---

CHANGELOG.md
docker/orchestrator-chaincode/Dockerfile
docker/orchestrator-server/Dockerfile

This updates:
- protoc-gen-go to v1.18.1 from v1.18.0
- grpc_health_probe to v0.4.12 from v0.4.11
- migrate to v1.28.1 from v1.28.0
- CI

chore: update docker image dependencies

---

CHANGELOG.md
chaincode/computetask/contract.go

At the time I created the disable output feature it was not tested as no client was using it. Today I introduced an end to end test that use this feature (https://github.com/Substra/substra-tests/pull/201) and it broke in distributed mode because the smart contract entry `DisableOutput` did not exit. This PR addresses that, by renaming the `DeleteOutput` smart contract entry to `DisableOutput` which is the right name.
End to end tests.

fix: rename DeleteOutput to DisableOutput in computetask smart contract

---

CHANGELOG.md
docs/assets/computetask.md
e2e/client/option.go
lib/asset/computetask.proto
lib/asset/computetask_validation.go
lib/asset/computetask_validation_test.go
lib/service/computetask.go
lib/service/computetask_test.go

This feature will allow to specify the worker on task creation. That's a first step to remove task-specific data and, eventually, task categories.
For tasks having a datamanager, the worker is inferred from the manager's owner and the input is **ignored**.
Tasks not having input data, such as our current aggregation tasks, explicitly setting the worker is mandatory.
For now, aggregate tasks will fallback to task-specific data if the worker is not set.
This means that there is some throwaway code here and there: it will disappear once all consumers have transitioned to the new field.
- unit test
- e2e

feat: assign worker from NewComputeTask

---

lib/service/computetask.go
lib/service/computetask_test.go

In #18 , I messed up the implementation and always used the aggregation data worker instead of just falling back in case the task worker was not set.
This PR fixes that.
- unit test

fix: only use aggregate worker as fallback

---

CHANGELOG.md
lib/asset/computetask.proto
lib/asset/computetask_validation.go
lib/asset/computetask_validation_test.go
lib/service/computetask_test.go

The backend does not send parent task keys since https://github.com/Substra/substra-backend/pull/455.
Let's remove this deprecated property.
- CI

chore: remove NewComputeTask.parent_task_keys

---

CHANGELOG.md
e2e/model_test.go
lib/service/model.go
lib/service/model_test.go
lib/service/performance.go
lib/service/performance_test.go

Events were not dispatched in the appropriate order: task output came before the referenced asset was registered.
Both models and performances were impacted.
- unit test were updated with a specific assertion on event registration order.

fix: task outputs events come after their asset creation

---

CHANGELOG.md
e2e/client/option.go
lib/asset/computetask.proto
lib/service/computetask.go
lib/service/computetask_test.go

Remove the worker field from aggregate task data since it was deprecated and not used by any consumers anymore.
e2e tests.
Result:
```
============ 110 passed, 7 skipped, 7 warnings in 559.00s (0:09:19) ============
```
Hello, it's me stealing cleanup PRs:

feat: remove worker field from aggregate task data

---

CHANGELOG.md
chaincode/model/contract.go
chaincode/model/contract_test.go
e2e/client/client.go
e2e/model_test.go
lib/asset/model.proto
lib/service/model.go
lib/service/model_test.go
server/distributed/adapters/model.go
server/standalone/handlers/model.go
server/standalone/handlers/model_test.go

The compute engine now use DisableOutput, DisableModel can be removed 🔥.
e2e tests.
Result:
```
============ 110 passed, 7 skipped, 7 warnings in 560.62s (0:09:20) ============
```

feat: remove DisableModel rpc

---

charts/orchestrator/CHANGELOG.md
charts/orchestrator/Chart.yaml
charts/orchestrator/README.md
charts/orchestrator/templates/deployment.yaml
charts/orchestrator/values.yaml

When running the orchestrator with TLS enabled in standalone mode the user needed to include the internal hostname `my-orchestrartor.orchestrator.svc.cluster.local` in his certificate to make the startup probe pass.
This is not ideal as you might not want to add this internal hostname in your public certificates.
With this change when `ingress.hostname` is set we use this server name to check the validity of the certificate.
Tested locally by deploying with Skaffold.

feat: check for the external hostname in the health probe

---

charts/orchestrator/README.md
charts/orchestrator/values.yaml

We used to mention secret in a location where we expected a configmap.
see here for the matching code: https://github.com/Substra/orchestrator/blob/ed12733031da57fd55e4bdf72f3ab8e0991642ad/charts/orchestrator/templates/deployment.yaml#L171-L181

docs: fix mention of secret where it should be configmap

---

CHANGELOG.md
lib/asset/computetask_validation.go
lib/asset/computetask_validation_test.go
lib/service/computetask.go
lib/service/computetask_test.go
server/standalone/migration/000050_allow_unknown_tasks.up.sql

This is a temporary change to ease future removal of task categories. By allowing unknown tasks and bypassing the task-specific data field, consumers are already able to create truly generic tasks.
relying on CI

feat: allow unknown task category

---

CHANGELOG.md
lib/service/performance.go

Following #56 , we should allow perf registration on any task category (we enforce that the algo has a perf output anyway).
- unit tests

feat: allow perf registration on any task

---

docker/orchestrator-chaincode/dependencies.json
docker/orchestrator-server/dependencies.json

Upgrade dependencies since Alpine doesn't keep old versions of packages in repos, leading to [docker build failure](https://github.com/Substra/orchestrator/actions/runs/3298943621)
Images used not to build, now they do.

fix: upgrade dependencies

---

.github/CODEOWNERS

This will allow the FL squad to approve boilerplate PRs such as dependency updates
I'm leaving Aurélien, Matthieu and Thibaud in expecting they will be removed later, since their expertise is still needed. But we could also remove them now since we can still ask for review.

chore: add FL squad as codeowners

---

.github/workflows/end2end.yml

The pg_dump version in e2e GitHub action does not work due to descrepancy between `pg_dump` client (version 14.6) and the `postgres` server (15)

build: Set postgresql version

---

CHANGELOG.md
chaincode/ledger/dbal.go
chaincode/ledger/dbal_computetask.go
lib/asset/computetask.proto
lib/persistence/computetask_dbal.go
lib/service/computetask.go
lib/service/computetask_test.go
lib/service/computetaskstate.go
lib/service/computetaskstate_test.go
server/standalone/dbal/computetask.go
server/standalone/dbal/computetask_test.go
server/standalone/migration/000052_remove-parent_task_key-in-compute-task.up.sql

- https://github.com/Substra/substra-backend/pull/554
- Remove `compute_task_parents`:
- in `ComputeTask`
- in gRPC communication
- remove `expanded_compute_tasks`
CI

refactor: remove parent task key

---

skaffold.yaml

- https://github.com/Substra/hlf-k8s/pull/147
- https://github.com/Substra/substra-backend/pull/574
Update skaffold schema to `v4beta2` due to migration to Skaffold version `2.x.x` which was compatible with our schemas.
CI

chore(skaffold): update skaffold to 2.1.0

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/config.yml

Signed-off-by: SdgJlbl <sarah.diot-girard@owkin.com>
Add templates for issues on GitHub.
Include a bug report form, a link to the documentation for documentation improvements, a link to Substra Slack for questions, and the option to open a blank (non templated) issue for all other needs.

chore: add issues templates

---

CHANGELOG.md
charts/orchestrator/CHANGELOG.md
charts/orchestrator/Chart.yaml

- A Performance in now unique regarding a compute task key, a metric key and a compute task output identifier ([#197](https://github.com/Substra/orchestrator/pull/197))
- Metric from Performance ([#213](https://github.com/Substra/orchestrator/pull/213))

chore: release 0.34.0

---

CHANGELOG.md
charts/orchestrator/CHANGELOG.md
charts/orchestrator/Chart.lock
charts/orchestrator/Chart.yaml

- Minor dependency updates. See commit history for more details.

chore: release 0.35.1

---

charts/orchestrator/README.md
examples/values/orchestrator-org-1-distributed.yaml
examples/values/orchestrator-org-1.yaml
examples/values/orchestrator-org-2-distributed.yaml

Changes the Ingress Class Annotation with `IngressClass` resource [as Ingress class annotation is deprecated](https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#deprecating-the-ingress-class-annotation)

fix(kubernetes): update deprecated annotation to use spec.ingressClassName

---

CHANGELOG.md
chaincode/main.go
server/distributed/chaincode/wallet.go

What is said in the title
Unit tests 🤞

chore: replace deprecated ioutil package with os

---

CHANGELOG.md
charts/orchestrator/CHANGELOG.md
charts/orchestrator/Chart.yaml

- Replace deprecated ioutil package with os ([#269](https://github.com/Substra/orchestrator/pull/269))

chore: release 0.36.0

---

docker/orchestrator-chaincode-init/dependencies.json

Increment the cURL version on `orchestrator-chaincode-init` to `8.3.0-r0`

chore(deps): bump curl to 8.3.0-r0

---

go.mod
go.sum

Revert #300 to avoid disruptions to the release process

revert: bumping golang.org/x/sync from 0.3.0 to 0.4.0

---

docker/orchestrator-chaincode-init/dependencies.json

See [build](https://github.com/Substra/orchestrator/actions/runs/6482399335/job/17601837680#step:10:205):
```
#7 2.592 ERROR: unable to select packages:
#7 2.641   curl-8.4.0-r0:
#7 2.641     breaks: world[curl=8.3.0-r0]
```

chore(docker/orchestrator-chaincode-init): curl 8.3.0-r0 -> 8.4.0-r0

---

.github/workflows/end2end.yml

Recent dependency update (#[bd9c1ed](https://github.com/Substra/orchestrator/commit/bd9c1ed88c656a9700ef355b521a2121fc8f26c6)) should have bumped the `postgres` version in e2e tests (see [upgrading](https://artifacthub.io/packages/helm/bitnami/postgresql#to-13-0-0)):
```txt
This major version changes the default PostgreSQL image from 15.x to 16.x. 
```

chore(.github/workflows): bump postgres image

---

e2e/client/client.go
lib/asset/function.proto
lib/service/function.go
lib/service/function_test.go
lib/service/functionstate.go
server/standalone/dbal/addressable.go
server/standalone/dbal/function.go

On top of https://github.com/Substra/orchestrator/pull/288.
We remove Image from NewFunction, and we create the Addressable Image with empty strings when we register the Function.
We create the `getOrAddAddressable` to avoid multiple creation of the empty Image Addressable.

fix: new function have no image

---

.github/workflows/helm.yml

Companion:
- https://github.com/Substra/substra-backend/pull/881
- https://github.com/Substra/orchestrator/pull/405
- https://github.com/Substra/substra-frontend/pull/333
Example of working worklfow (with fake publish):
- https://github.com/Substra/substra-backend/actions/runs/8628929572

chore: allow alpha charts publication

---

changes/432.changed
changes/432.fixed
e2e/computeplan_test.go
lib/persistence/computeplan_dbal.go
lib/service/computeplan.go
lib/service/computetaskstate.go
server/standalone/dbal/computeplan.go
server/standalone/dbal/computeplan_test.go

check is plan.terminated when calling IsPlanRunning instead of changing the status of the task, cause it does not change the behaviour of `IsPlanRunning` (checked before changing task status).
This PR revert a part of https://github.com/Substra/orchestrator/pull/427 and closes FL-1593

fix: check plan.IsTerminated on IsPlanRunning

---

lib/service/computetask.go

fix: check outputAsset array length before deactivating them

---

charts/orchestrator/CHANGELOG.md
charts/orchestrator/Chart.yaml
charts/orchestrator/README.md
charts/orchestrator/templates/_helpers.tpl
charts/orchestrator/values.yaml

feat: make init container image customizable
